### ISSUE TITLE
Jupyter Version ？

### ISSUE THREAD

**Issue by TerenceLiu98** [ryancheunggit/Calculus-with-Python#4]
Hi, I am now using ur book.and learning ur book wiht the Jupyter notebook. But I added some my understanding in the content. This is the link: https://github.com/TerenceLiu98/Self_Study

**Comment by ryancheunggit** [comment]
Hey your notebook is very cool! Sorry, I was troubled at my day job and wasn't able to create notebooks myself.. I will add links to your notebook.

**Comment by TerenceLiu98** [comment]
@ryancheunggit thx!

**Comment by TerenceLiu98** [comment]
I think we can close this issue.
